* :muscle: muscle-assert :muscle: [[https://circleci.com/gh/ayato-p/muscle-assert/tree/master][https://circleci.com/gh/ayato-p/muscle-assert/tree/master.svg?style=svg]] [[https://codecov.io/gh/ayato-p/muscle-assert][https://codecov.io/gh/ayato-p/muscle-assert/branch/master/graph/badge.svg]]

  Muscle Assert for Clojure.

  Latest version is

  [[https://clojars.org/ayato_p/muscle-assert][https://img.shields.io/clojars/v/ayato_p/muscle-assert.svg]]

** Usage

   Merge the following with your project.clj or profiles.clj

   #+begin_src clojure
   {:dependencies [[ayato_p/muscle-assert "0.1.0"]]
    :injections [(require 'muscle-assert.core)
                 (muscle-assert.core/activate!)]}
   #+end_src

   Then run your tests via =lein test= or any compatible test runner.


** What is Muscle Assert

*** Japanese articles

    - [[http://pocketberserker.hatenablog.com/entry/2016/06/02/143727][Persimmon用アサーションライブラリMuscleAssertを作った]]
    - [[http://bleis-tift.hatenablog.com/entry/hello-muscle-assert][続・そろそろPower Assertについてひとこと言っておくか]]

** License


   The MIT License (MIT)

   Copyright (c) 2016 Ayato Nishimura

   Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

   The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
